on:
  push:
    branches:
      - main
name: release-please
permissions: read-all|write-all
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
#           token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          package-name: release-please-action
          prerelease: true
